corrected the nav-bar icon rotate bug
PatMiracle/WebChatIo pull request #1
Opened 2023-04-02 23:10 UTC by Sovrano28

nav-bar icon is supposed to rotate on click not and not on hover. this was corrected.

2023-04-03 08:02 UTC, PatMiracle requested changes

2023-04-03 08:02 UTC, PatMiracle commented on src/components/Nav/Nav.jsx
## Using document.querySelector in React

You can use the querySelector and querySelectorAll within React. The downside it that you can lose the reference to the DOM element due to Reacts Reactivity. The solution is to use the useRef hook provided by react to store a reference to the DOM element.

2023-04-03 19:38 UTC, Sovrano28 commented on src/components/Nav/Nav.jsx
I'll correct that now. thanks @PatMiracle

2023-04-03 19:43 UTC, Sovrano28 commented
I have made the corrections, you like can review it @PatMiracle

2023-04-04 04:15 UTC, PatMiracle approved these changes

2023-04-04 04:18 UTC, PatMiracle approved these changes
## Good work
This is better. 🤝🏾

2023-04-04 04:19 UTC, PatMiracle commented
## Nice one

I think we can move to making an interface for the chat center.

2023-04-04 04:20 UTC, PatMiracle commented
## Nice one

I think we can move to making an interface for the chat center.

2023-04-04 04:23 UTC, merged

2023-04-04 19:31 UTC, Sovrano28 commented
let's go there! 😁💪🏾